development:
  adapter: async
  # url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:f89538fa7d81c7d3669605543ab331ba@hammerjaw.redistogo.com:11743/
  channel_prefix: finals_project_production
