meta_product_name: "Develop For Good!"
meta_title: "Dev For Good - Coding for good! Helping NGOs and new Devs!"
meta_description: "Work on projects that matter. Connecting NGOs and new developers for a mutually benefitial partnership!"
meta_image: "logo.png" # should exist in `app/assets/images/`
